name: Update README with Git Time Stats

on:  # Run on push to main branch
  push:
    branches:
      - main
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes to README
    
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate stats
      
      - name: Calculate Git Time Stats
        id: git-time-stats
        uses: theboringdotapp/git-time-stats-action@v1
        with:
          session-gap: 30      # Minutes gap between sessions (default: 30)
          min-session: 5       # Minimum session duration in minutes (default: 5)
          max-session: 8       # Maximum session duration in hours (default: 8)
          readme-path: 'README.md'
          commit-changes: 'true'
          commit-message: 'docs: Update time stats in README [skip ci]' 